2019-02-11T15:17:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_hardware.py", line 37, in connect
    trigger_source=self.trigger_source.val, trigger_edge=self.trigger_edge.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 24, in __init__
    self.Task()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 34, in Task
    self.task.timing.cfg_implicit_timing(sample_mode=nidaqmx.constants.AcquisitionType.HW_TIMED_SINGLE_POINT, samps_per_chan=round(self.freq))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\_task_modules\timing.py", line 2911, in cfg_implicit_timing
    check_for_error(error_code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Requested value is not a supported value for this property. The property value may be invalid because it conflicts with another property.
Property: DAQmx_SampQuant_SampMode
Requested Value: DAQmx_Val_HWTimedSinglePoint
Possible Values: DAQmx_Val_FiniteSamps, DAQmx_Val_ContSamps

Task Name: _unnamedTask<0>

Status Code: -200077

