2019-01-15T11:42:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 120, in set_num_samples
    self.task.timing.cfg_samp_clk_timing(samps_per_chan = self.num_samples )
TypeError: cfg_samp_clk_timing() missing 1 required positional argument: 'rate'

